INSERT INTO PRODUCT (ID, NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANITITY)
VALUES (1, 'iPhone 15 Pro', 'Latest Apple smartphone', 'Apple', 1299.99, 'Electronics', DATE '2024-09-15', TRUE, 50);

INSERT INTO PRODUCT (ID, NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANITITY)
VALUES (2, 'Galaxy S24', 'Flagship Samsung phone', 'Samsung', 1199.99, 'Electronics', DATE '2024-10-01', TRUE, 40);

INSERT INTO PRODUCT (ID, NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANITITY)
VALUES (3, 'Sony WH-1000XM5', 'Noise-canceling headphones', 'Sony', 349.99, 'Audio', DATE '2023-08-10', TRUE, 30);

INSERT INTO PRODUCT (ID, NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANITITY)
VALUES (4, 'Nike Air Max', 'Running shoes', 'Nike', 199.99, 'Footwear', DATE '2024-05-20', TRUE, 100);

INSERT INTO PRODUCT (ID, NAME, DESC, BRAND, PRICE, CATEGORY, RELEASE_DATE, AVAILABLE, QUANITITY)
VALUES (5, 'Asus ROG Laptop', 'Gaming laptop with RTX 4070', 'Asus', 2199.00, 'Computers', DATE '2024-11-11', TRUE, 25);
